import { createSlice } from '@reduxjs/toolkit'
import type { PayloadAction } from '@reduxjs/toolkit'
import { RootState } from './store';

export type AppState = {
  appName: string | null;
}

const initialState: AppState = {
  appName: null
}

export const appSlice = createSlice({
  name: 'app',
  initialState: initialState,
  reducers: {
    setAppName: (state: AppState, action: PayloadAction<string>) => {
      const name: string = action.payload;
      state.appName = name;
    }
  }
})

// Actions are generated by createSlice for each reducer 
export const { 
  setAppName
} = appSlice.actions

// Convenience for accessing state attributes
export const selectAppName = (state: RootState) => state.app.appName;

export default appSlice.reducer